from dmitryrck/ruby:ready0.91

env \
  DEBIAN_FRONTEND=noninteractive \
  NODE_VERSION=12.18.4

run \
  npm install -g \
    babel-eslint \
    eslint@8.19.0 \
    eslint-config-prettier \
    eslint-config-standard \
    eslint-plugin-html \
    eslint-plugin-import@latest \
    eslint-plugin-node@latest \
    eslint-plugin-prettier \
    eslint-plugin-prettier-vue \
    eslint-plugin-promise@latest \
    eslint-plugin-standard@latest \
    eslint-plugin-vue@latest \
    eslint-plugin-vue@next \
    prettier
